### ISSUE TITLE
Can't Install this from AUR

### ISSUE THREAD

**Issue by AlePini** [virtualsquare/umps3#1]
After compiling correctly, it just refuse to continue, saying that "/usr/local/share/man already exists"

**Comment by berdav** [comment]
Seems to be a problem of the PKGBUILD.
@mattiabiondi is working on a fix, in the meanwhile downloading the attached patch and doing:

```
$ git clone https://aur.archlinux.org/umps3-git.git
$ cd umps3-git
$ git apply ../0001-Fixed-problem-with-usr-local-symlink.patch
$ makepkg
$ sudo pacman -U ./umps3-git-3.0.4.r2.gb7cb8af-2-x86_64.pkg.tar.zst
```

Seems to compile and install the package correctly.
0001-Fixed-problem-with-usr-local-symlink.patch:
```
From 2820329ddc5b24046e172b06c9928d317a695b0a Mon Sep 17 00:00:00 2001
From: Davide Berardi <berardi.dav@gmail.com>
Date: Fri, 20 Nov 2020 12:57:18 +0000
Subject: [PATCH] Fixed problem with /usr/local symlink

---
 PKGBUILD | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/PKGBUILD b/PKGBUILD
index 5a80940..4c1f846 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -3,7 +3,7 @@ _name=umps
 _ver=3
 pkgname=$_name$_ver-git
 pkgver=3.0.4.r2.gb7cb8af
-pkgrel=1
+pkgrel=2
 pkgdesc="Virtual machine simulator based around the MIPS R2/3000 microprocessor."
 arch=('x86_64')
 url="https://github.com/virtualsquare/umps3"
@@ -20,7 +20,8 @@ pkgver() {
 
 build() {
   cmake -B build -S $pkgname \
-       -DCMAKE_BUILD_TYPE=Release
+       -DCMAKE_BUILD_TYPE=Release \
+       -DCMAKE_INSTALL_PREFIX=/usr
   make -C build
 }
 
-- 
2.29.2
```

**Comment by mattiabiondi** [comment]
Thanks @AlePini for reporting the issue, and thanks @berdav for solving it!

PKGBUILD for both [umps3](https://aur.archlinux.org/packages/umps3/) and [umps3-git](https://aur.archlinux.org/packages/umps3-git/) updated, @AlePini can you confirm it now installs correctly?

**Comment by AlePini** [comment]
I eneded up installing it from source.
But it works too from AUR now. Thanks :+1:
